name: Providers

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Python3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Setup
      run: python -m pip install -r requirements_ping.txt
    - name: Run ping.py
      run: |-
        python t.py