name: Providers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Ping
      run: |-
        python -c "import httpx;from yarl import URL;host=URL('https://hachirumi.com').host;resp=httpx.get(f'https://api.justyy.workers.dev/api/ping/?host={host}&cached').text;print(0 if resp == 'null' else resp.split('\/')[-3])"