name: Providers

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |-
        sudo python3 -m pip3 install --upgrade pip
        sudo python3 -m pip3 install -r requirements_ping.txt
    - name: Run ping.py
      run: |-
        sudo python t.py